curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Excelente atendimento ao cliente!"}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Serviço de entrega rápido e eficiente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Equipe extremamente prestativa e amigável."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Produtos de alta qualidade."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Fiquei impressionado com a gentileza dos funcionários."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Ótimo ambiente e decoração."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"A empresa realmente se preocupa com seus clientes."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Sempre recebo assistência imediata quando necessário."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Muito satisfeito com a experiência global."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "message":"Parabéns pelo excelente serviço prestado!"}'

curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Tempo de espera na fila de atendimento é muito longo."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Prazos de entrega não são cumpridos."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Atendimento ao cliente deixa muito a desejar."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Qualidade dos produtos caiu recentemente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Problemas frequentes de comunicação com a empresa."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Fui tratado de forma rude por um funcionário."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Preços dos produtos estão muito altos."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Dificuldade em encontrar informações no site."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Demora para resolver problemas e reclamações."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "message":"Não estão acompanhando as tendências do mercado."}'

curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Considere oferecer opções de entrega expressa."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Melhore a interface do site para facilitar a navegação."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Ofereça descontos especiais para clientes fiéis."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Amplie a variedade de produtos disponíveis."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Crie um programa de fidelidade para recompensar os clientes."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Invista em treinamento para melhorar o atendimento."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Disponibilize um canal de suporte 24 horas."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Faça pesquisas de satisfação periodicamente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Promova mais campanhas de marketing."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "message":"Aprimore a comunicação com os clientes por e-mail."}'
