curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Excelente atendimento ao cliente!"}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Serviço de entrega rápido e eficiente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Equipe extremamente prestativa e amigável."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Produtos de alta qualidade."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Fiquei impressionado com a gentileza dos funcionários."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Ótimo ambiente e decoração."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "A empresa realmente se preocupa com seus clientes."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Sempre recebo assistência imediata quando necessário."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Muito satisfeito com a experiência global."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"ELOGIO", "Parabéns pelo excelente serviço prestado!"}'

curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Tempo de espera na fila de atendimento é muito longo."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Prazos de entrega não são cumpridos."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Atendimento ao cliente deixa muito a desejar."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Qualidade dos produtos caiu recentemente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Problemas frequentes de comunicação com a empresa."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Fui tratado de forma rude por um funcionário."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Preços dos produtos estão muito altos."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Dificuldade em encontrar informações no site."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Demora para resolver problemas e reclamações."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"CRITICA", "Não estão acompanhando as tendências do mercado."}'

curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Considere oferecer opções de entrega expressa."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Melhore a interface do site para facilitar a navegação."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Ofereça descontos especiais para clientes fiéis."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Amplie a variedade de produtos disponíveis."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Crie um programa de fidelidade para recompensar os clientes."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Invista em treinamento para melhorar o atendimento."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Disponibilize um canal de suporte 24 horas."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Faça pesquisas de satisfação periodicamente."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Promova mais campanhas de marketing."}'
curl -X POST http://localhost:8080/api/feedback/envio -H 'Content-Type: application/json' -d '{"type":"SUGESTAO", "Aprimore a comunicação com os clientes por e-mail."}'
